# Generated by Django 3.2.8 on 2023-12-15 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockfunds',
            name='user_email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
