# Generated by Django 3.2.8 on 2023-12-15 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rolebased', '0004_contactinformation_message_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('change', models.FloatField()),
                ('percentageChange', models.FloatField()),
                ('volume', models.IntegerField()),
            ],
        ),
    ]
