# Generated by Django 4.2.4 on 2023-12-18 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rolebased', '0005_stockdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='aadhaarcard_image',
            field=models.ImageField(blank=True, null=True, upload_to='aadhaarcards/'),
        ),
        migrations.AddField(
            model_name='user',
            name='pancard_image',
            field=models.ImageField(blank=True, null=True, upload_to='pancards/'),
        ),
    ]
