# Generated by Django 4.0.6 on 2023-12-24 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rolebased', '0006_user_aadhaarcard_image_user_pancard_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('user_id', models.CharField(max_length=50)),
                ('utr_number', models.CharField(max_length=50)),
                ('screenshot', models.ImageField(upload_to='screenshots/')),
            ],
        ),
    ]
